name: 'Appknox GitHub Action'
description: 'Ensure your mobile applications are secure'
author: 'Appknox'
inputs:
  appknox_access_token:
    description: 'Personal Access Token on Appknox'
    required: true
  file_path:
    description: 'Path to the mobile application binary (apk/ipa)'
    required: true
  risk_threshold:
    description: 'Minimum risk. Valid options are LOW, MEDIUM, HIGH, CRITICAL. Defaults to "LOW"'
    required: true
    default: 'LOW'
  sarif:
    description: 'Enable SARIF format report. Defaults to false'
    default: 'Disable'
  api_host:  # New input parameter
    description: 'The API host to use. Can be a region like "uae", "saudi", "europe", or a custom URL'
    required: false
    default: 'secure.appknox.com'  # Default to the standard API host
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/index.js'
