name: 'Appknox GitHub action'
description: 'Ensure your mobile application are secure'
author: 'Appknox'
inputs:
  appknox_access_token:
    description: 'Personal Access Token on Appknox'
    required: true
  file_path:
    description: 'Path to the mobile application binary (apk/ipa)'
    required: true
  risk_threshold:
    description: 'Minimum risk. Valid options are LOW, MEDIUM, HIGH, CRITICAL. Defaults to "LOW"'
    required: true
    default: 'LOW'
  sarif:
    description: 'Enable SARIF format report. Defaults to false'
    default: 'Disable'
  region:  # New input parameter
    description: 'The Appknox Regions to use. Can be a region like `"Global"`, `"Saudi"`. By default it is `"Global"`'
    required: false
    default: 'secure.appknox.com'  # Default to the standard region
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/index.js'
