name: Mobile App Security Scan

on:
  push:
    branches:
      - main
    workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Appknox Security Scan
        uses: appknox/appknox-github-action@1.1.2
        with:
          appknox_access_token: ${{ secrets.APPKNOX_ACCESS_TOKEN }}
          file_path: app/build/outputs/apk/debug/app-debug.apk
          risk_threshold: HIGH
          region: 'https://api.appknox.com/api'
